<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-CDAJ1UEH" failures="3" tests="5"
	name="Test" time="42.126" errors="0" timestamp="2024-11-07T16:11:58 IST">
	<testcase classname="Module1.DataDrivenTest" name="testdatadriven"
		time="9.995" />
	<testcase classname="Module1.DataDrivenTest" name="testdatadriven"
		time="7.162">
		<failure type="java.lang.AssertionError"
			message="Login Fail expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login Fail expected [true] but found [false]
at Module1.DataDrivenTest.testdatadriven(DataDrivenTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
	</testcase> <!--
	testdatadriven -->
	<testcase classname="Module1.DataDrivenTest" name="testdatadriven"
		time="9.382" />
	<testcase classname="Module1.DataDrivenTest" name="testdatadriven"
		time="7.212">
		<failure type="java.lang.AssertionError"
			message="Login Fail expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login Fail expected [true] but found [false]
at Module1.DataDrivenTest.testdatadriven(DataDrivenTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
	</testcase> <!--
	testdatadriven -->
	<testcase classname="Module1.DataDrivenTest" name="testdatadriven"
		time="7.23">
		<failure type="java.lang.AssertionError"
			message="Login Fail expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login Fail expected [true] but found [false]
at Module1.DataDrivenTest.testdatadriven(DataDrivenTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
	</testcase> <!--
	testdatadriven -->
</testsuite> <!--
Test -->
